import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import UserAuth from "@/models/UserAuth";
import favicon from "@/public/favicon.png";

const nunito = Nunito({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Sprinlist",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: favicon.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <UserAuth>
          {children}
          <Toaster />
        </UserAuth>
      </body>
    </html>
  );
}
