version: '3.8'

services:
  mysql:
    image: mysql:5.7  # Usando a versão 5.7 do MySQL
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: todolist  # Senha do usuário root
      MYSQL_DATABASE: todolist       # Nome do banco de dados a ser criado
      MYSQL_USER: todolist                  # Nome do usuário do banco de dados
      MYSQL_PASSWORD: todolist      # Senha do usuário do banco de dados
    ports:
      - "3306:3306"  # Mapeando a porta 3306 do contêiner para a porta 3306 do host
    volumes:
      - mysql_data:/var/lib/mysql  # Persistência de dados

volumes:
  mysql_data:  # Definindo o volume para persistir os dados do MySQL
